name: Actualizar feed Meta

on:
  workflow_dispatch:

  schedule:
    - cron: "30 0 * * *"

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Regenerar feed Prestashop
        run: |
          curl -L "https://www.joyeriaparejo.com/module/gmerchantfeedes/generation?key=3&token=c470ff7b48edea476cc8ff978c0f42e1&only_rebuild=1"

      - name: Esperar generación
        run: sleep 20

      - name: Descargar nuevo feed
        run: |
          curl -L "https://www.joyeriaparejo.com/module/gmerchantfeedes/generation?key=3&token=c470ff7b48edea476cc8ff978c0f42e1&only_download=1" -o facebook-feed.xml

      - name: Commit si hay cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add facebook-feed.xml

          if git diff --cached --quiet; then
            echo "Sin cambios"
            exit 0
          fi

          git commit -m "Actualización automática del feed"
          git push
